### ISSUE TITLE
add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by santoshvijapure** [santoshvijapure/DS_with_hacktoberfest#21]
you can take reference of [https://github.com/stevemao/github-issue-templates](https://github.com/stevemao/github-issue-templates)

**Comment by Kvaibhav01** [comment]
Hi, @santoshvijapure I would like to work on this. What type of issue template do you need from the different categories that exist on the link?

**Comment by santoshvijapure** [comment]
create a custom one with a checklist of all 3 tasks mentioned in README.md.
