### ISSUE TITLE
Implement Queue

### ISSUE THREAD

**Issue by pprathameshmore** [santoshvijapure/DS_with_hacktoberfest#3]
Implement Queue data structure.

**Comment by 20harshita** [comment]
can i take this issue ? please assign on my name

**Comment by pprathameshmore** [comment]
Done! @20harshita

**Comment by 20harshita** [comment]
I am working on this issue . Please assign

**Comment by stevhens** [comment]
I have implemented Queue in Swift #124

**Comment by himanshujain171** [comment]
@pprathameshmore  Can you assign this issue to me...I have a better and efficient algorithm for this...
